### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by ChakshuGautam** [AmakrushAI/app#10]
@aashutosh-samagra calculate delta with the Figma design and phase it out.

Figma board - [Link](https://www.figma.com/file/ZwFg8Dy2LkPIG2xwwuK0qH/AmaKrushi-AI?node-id=0-1&t=Ehjw9RUnT8yb3esu-0)

- [x] #11 
- [x] #12 
- [x] #13 
- [x] #14 
- [ ] #15 
- [x] #16 
- [x] #17 
- [x] #71 
- [x] #79 

@prtkjakhar will own this.

**Comment by prtkjakhar** [comment]
[screen-capture.webm](https://user-images.githubusercontent.com/65057795/231187831-af967db9-5a11-4c45-a893-b2b02cf1b806.webm)
Does it cover issues #12 #13 #14 #16 #17 @aashutosh-samagra ?

**Comment by prtkjakhar** [comment]
PR for these changes: #59

**Comment by prtkjakhar** [comment]
![Image](https://user-images.githubusercontent.com/65057795/231733032-8775648a-1377-4574-be92-164157c27ed2.png)

Does it look okay?
