### ISSUE TITLE
Pop up for showing call centre information

### ISSUE THREAD

**Issue by vijeeth-impactatscale** [AmakrushAI/app#105]
Need a popup with a message that "Please call 155333 to resolve your query with Ama Krushi Call centre" whenever a farmer clicks on dissatisfied (red thumbs down) after any response to query. Eventually, this should direct user to dialpad with number already dialed.

**Comment by prtkjakhar** [comment]
Have implemented a basic alert box that opens the dialer app on mobile when clicked. Changes are live on [staging](https://app.staging.akai.samagra.io/). Waiting for feedback to push on prod.
cc: @aashutosh-samagra

**Comment by aashutosh-samagra** [comment]
UI Updated on [Figma](https://www.figma.com/file/ZwFg8Dy2LkPIG2xwwuK0qH/AmaKrushi-AI?type=design&node-id=0-1&t=WoDtHiGwFEe19Bxm-0)
