### ISSUE TITLE
STT Feature

### ISSUE THREAD

**Issue by ChakshuGautam** [AmakrushAI/app#110]
@aashutosh-samagra to get feedback.

- [ ] Flag to set models to STT.
- [ ] Publish the list to this ticket.

**Comment by aashutosh-samagra** [comment]
- [ ] *Translates in hinglish with text coming up in english* - Even if odiya tab is selected, translation happens in hinglish, image attached below for reference. 

![Image](https://github.com/AmakrushAI/app/assets/122012226/164e2c26-1da2-4a7a-aad0-947636cfaefc)

- [ ] *Translation of responses breaks in between* -  A response coming in Hindi suddenly throws a word in English in between. Image attached below for reference. 

![Image](https://github.com/AmakrushAI/app/assets/122012226/85848b75-68cf-4b24-9758-c359bc58ca01)

**Comment by ChakshuGautam** [comment]
@geeky-abhishek to add model IDs to name table?

**Comment by ChakshuGautam** [comment]
@ChakshuGautam to add ASR from Google, Azure.

**Comment by geeky-abhishek** [comment]
{
  "Hindi-Odia": [
    {
      name: "Vakyansh ASR Batch - Hindi",
      modelId: "63c9585dc37c442f683d69dd",
    },
    {
      name: "Speech Lab IITM ASR - Hindi",
      modelId: "6387b32886369150cb004350",
    },
  ],
  "Odia-Hindi":[
    {
      name : "AI4Bharat IndicWav2Vec ASR Batch - Odia",
      modelId: "6210c14a751fc8007d240841"
    },
    {
      name : "Vakyansh ASR Batch - Odia",
      modelId: "63c9582bc37c442f683d69d9"
    }
  ],
  "Eng-Odia" :[
    {
      name : "AI4Bharat IndicWav2Vec ASR Batch - English",
      modelId :"620fb95d751fc8007d24083a"
    },
    {
      name : "Vakyansh ASR Batch - English",
      modelId :"63c9586ea0e5e81614ff96a8"
    },
    {
      name : "OpenAI Whisper ASR Batch - English (base.en)",
      modelId :"6348eb07fd966563f61bc2c6"
    },
    {
      name : "Speech Lab IITM ASR - English",
      modelId :"6387b54086369150cb004351"
    },
    {
      name : "OpenAI Whisper ASR Batch - English (medium.en)",
      modelId :"641c0be440abd176d64c3f92"
    }
  ]
};
@ChakshuGautam ASR Models added

**Comment by aashutosh-samagra** [comment]
Confirmer model for Odiya to be updated - 

https://colab.research.google.com/drive/1EU2BWYO2kkR4wCZgXm13gG3Uh4ZJasB6?usp=sharing#scrollTo=XSgkQmjiKL4a

api key for AI4Bharat STT model: 
nLjwgV6Yj7_p-3tfX269cxMNevYOWnzZrkMJtQREEZlDUltoPlOsbzCW_iHjitbO
