### ISSUE TITLE
Downtime Page

### ISSUE THREAD

**Issue by ChakshuGautam** [AmakrushAI/app#113]

**Comment by aashutosh-samagra** [comment]
Link to figma board - [Link](https://www.figma.com/file/ZwFg8Dy2LkPIG2xwwuK0qH/AmaKrushi-AI?type=design&node-id=0-1&t=WoDtHiGwFEe19Bxm-0)

Odiya Translation - 

- We're temporarily down - କିଛି ସମୟ ପାଇଁ ସର୍ଭର ଡାଉନ୍ ଅଛି |
- we are experiencing high user volume......... - ଆମେ ଏହି ମୁହୂର୍ତ୍ତରେ ଉଚ୍ଚ ଉପଭୋକ୍ତା ଏହାକୁ ବ୍ୟବହାର କରୁଥିବା ର‌ ଅନୁଭବ କରୁଛୁ | ଦୟାକରି କିଛି ସମୟ ପରେ ଲଗଇନ୍ କରିବାକୁ ଚେଷ୍ଟା କରନ୍ତୁ |
- Retry - ପୂର୍ଣ୍ଣବାର ଚେଷ୍ଟା କରନ୍ତୁ
![image](https://github.com/AmakrushAI/app/assets/122012226/2537b216-8697-4295-a304-4e03b1f97094)
