### ISSUE TITLE
Adding a menu bar

### ISSUE THREAD

**Issue by aashutosh-samagra** [AmakrushAI/app#13]
We want to add a menu bar to the website that allows users to navigate to different pages. The menu bar should have 3 navigation toggles at the bottom for navigating to - Home page, Chat page, and More options. The more options segment should have links to User profile, FAQs, Feedback and Logout.

**Comment by aashutosh-samagra** [comment]
User Profile - @aashutosh-samagra

**Comment by prtkjakhar** [comment]
**Menu bar buttons working to pages:** 
- [x] More options page
- [x] Chat history page
- [x] Home page

**Additional Screens/Features inside More Page**
- [ ] User Profile - `deprioritized to Beta`
- [x] FAQs Page
- [x] Feedback page
- [x] Logout functionality

**Comment by ChakshuGautam** [comment]
@prtkjakhar to create a new ticket for pending items.

**Comment by prtkjakhar** [comment]
Moved to #87
