### ISSUE TITLE
Adding chat history

### ISSUE THREAD

**Issue by aashutosh-samagra** [AmakrushAI/app#14]
Adding the below 3 sections as per the mockups :

1. Chat History  - [Link](https://www.figma.com/proto/ZwFg8Dy2LkPIG2xwwuK0qH/AmaKrushi-AI?node-id=13%3A19104&scaling=scale-down&page-id=0%3A1&starting-point-node-id=3%3A4)
2. User Feedback - [Link](https://www.figma.com/proto/ZwFg8Dy2LkPIG2xwwuK0qH/AmaKrushi-AI?node-id=7%3A15967&scaling=scale-down&page-id=0%3A1&starting-point-node-id=3%3A4)
3. FAQs - [Link](https://www.figma.com/proto/ZwFg8Dy2LkPIG2xwwuK0qH/AmaKrushi-AI?node-id=7-16648&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A4)

**Comment by prtkjakhar** [comment]
Mockup for the history page created. Need @Amruth-Vamshi or @geeky-abhishek help to integrate the history functionality.

**Comment by ChakshuGautam** [comment]
Blocked on BFF @ChakshuGautam

**Comment by aashutosh-samagra** [comment]
Minor UI changes in chat history page required (sharing option to be added). Will share the revised mockup.
