### ISSUE TITLE
Deploy: Telemetry (Add Firebase)

### ISSUE THREAD

**Issue by aashutosh-samagra** [AmakrushAI/app#5]
KPIs to be tracked - [Link](https://docs.google.com/spreadsheets/d/1C-AsJ-WcYww2avlTblhBEbgiDGw9RyQmQSfCsVEvLJs/edit#gid=1532674054)

SN | KPI
-- | --
1 | Total users (SQL)
2 | Active users (SQL)
3 | Total queries asked (SQL)
4 | Avg time spent per session (Firebase)
5 | Avg response time per query (SQL)
6 | Query response rate (SQL)
7 | Feedback forms filled (SQL)
8 | Average feedback received (SQL)

Superset is to be wired up. @singhalkarun to share read-only access to @vijeeth-impactatscale

**Comment by ChakshuGautam** [comment]
@geeky-abhishek to figure out how this can be added to CI.

**Comment by ChakshuGautam** [comment]
- Staging
- Production

**Comment by prtkjakhar** [comment]
Firebase dashboard view

![Image](https://user-images.githubusercontent.com/65057795/232705359-9771b293-9a99-4303-b4b1-80de72dc37bf.png)
