### ISSUE TITLE
Feat: User Feedback and FAQ section

### ISSUE THREAD

**Issue by aashutosh-samagra** [AmakrushAI/app#6]

**Comment by ChakshuGautam** [comment]
@prtkjakhar to come up with REST API Design for `/<>` and @Amruth-Vamshi to build those API.

**Comment by prtkjakhar** [comment]
- Need two APIs because there are two different buttons, one for star rating submission and one for descriptive feedback submission. APIs can be named something like ```/starRating``` and ```/feedback``` or if @Amruth-Vamshi comes up with something else that is also fine.
- Need content to put inside FAQ drop-downs. @aashutosh-samagra

**Comment by ChakshuGautam** [comment]
@prtkjakhar  to add curl request and sample response.

**Comment by prtkjakhar** [comment]
Sample curl requests for both star rating submission and feedback submission:
`curl -X POST -H "Content-Type: application/json" -d '{"rating": 4}' https://your-api-endpoint.com/feedback`
`curl -X POST -H "Content-Type: application/json" -d '{"feedback": "example feedback data"}' https://your-api-endpoint.com/feedback`

Also, @Amruth-Vamshi I am not sure if both APIs can have the same endpoint and if the server can check the contents of the request to determine whether it is a star rating or descriptive textbox feedback submission.

**Comment by Amruth-Vamshi** [comment]
@prtkjakhar Yes, we can have a single API for feedback keeping review an optional field.
EndPoint: `POST /feedback`
Request body: 
`{
"phone_number": "1234567890", (mandatory field)
"review": "review that user writes" (will be and optional field),
"rating": 4 (mandatory field)
}`
Response: will be same as request body if user submits `review` it will be part of response else review will be null.

**Comment by prtkjakhar** [comment]
I don't think we can keep rating as a mandatory field because there are two separate submit buttons hence the user can either just submit the star rating or just submit the written feedback. Both will have to be optional.

**Comment by Amruth-Vamshi** [comment]
@prtkjakhar oh, got it. in that case any one of these (feedback,rating) should be given in the input along with phone number.

**Comment by ChakshuGautam** [comment]
FAQs Content - @aashutosh-samagra 
Feedback APIs - @Amruth-Vamshi to share postman collection

**Comment by aashutosh-samagra** [comment]
FAQ Content - [Link](https://docs.google.com/spreadsheets/d/1C-AsJ-WcYww2avlTblhBEbgiDGw9RyQmQSfCsVEvLJs/edit#gid=840834943)

**Comment by ChakshuGautam** [comment]
@Amruth-Vamshi create a ticket to add it to Admin.

**Comment by prtkjakhar** [comment]
Have added faq API (#75), you will see FAQs after adding them to the admin console.

![Image](https://user-images.githubusercontent.com/65057795/233710518-0e1024fe-e809-4b86-9938-89ad07ecbe8c.png)
