### ISSUE TITLE
Coming Soon Page

### ISSUE THREAD

**Issue by ChakshuGautam** [AmakrushAI/app#70]
Map to - Profile page

@aashutosh-samagra to design. @vijeeth-impactatscale to review.

**Comment by aashutosh-samagra** [comment]
Design - [Link](https://www.figma.com/proto/ZwFg8Dy2LkPIG2xwwuK0qH/AmaKrushi-AI?node-id=528-21515&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A4)

**Comment by prtkjakhar** [comment]
![Image](https://user-images.githubusercontent.com/65057795/233632948-868ddeae-e028-43c7-acd3-dcf82b56a20b.png)
