### ISSUE TITLE
Add functionality for showing PDF

### ISSUE THREAD

**Issue by ChakshuGautam** [AmakrushAI/app#71]
@aashutosh-samagra to design.

**Comment by aashutosh-samagra** [comment]
Design - [Link](https://www.figma.com/proto/ZwFg8Dy2LkPIG2xwwuK0qH/AmaKrushi-AI?node-id=571-21687&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A4)

**Comment by prtkjakhar** [comment]
Have implemented the buttons. Need some google drive link to attach PDFs with them.

![Image](https://user-images.githubusercontent.com/65057795/233633176-07f63357-a046-4218-9cef-dc9c8c17c243.png)

**Comment by ChakshuGautam** [comment]
- [ ] User Stories to be added
- [ ] Where are we hosting the PDFs? - Google Drive
- [ ] Prateek to implement

**Comment by aashutosh-samagra** [comment]
1. PDF download/view

- The user should be able to view the user manual in a new tab upon clicking on the button (enable simultaneously download feature also)

2. Dial Button

- Implemented in mockups

3. Hosting of PDFs

- To be hosted on Samagra's google drive

**Comment by ChakshuGautam** [comment]
@prtkjakhar
1. Add it to flagsmith
2. Add components 1 and 2 to flagsmith

**Comment by prtkjakhar** [comment]
Added functionality to: 
 - edit dialer number
 - show/hide whole dialer box
 - show/hide pdf download buttons
 - edit english and odia pdf links



![Image](https://user-images.githubusercontent.com/65057795/234265213-fc62970e-8755-4d32-8a4f-b52ffb1fad7b.png)

**Comment by aashutosh-samagra** [comment]
@prtkjakhar , can you also add a feature flag for the "download" and "share" buttons on the chat page

**Comment by prtkjakhar** [comment]
Added.


![Image](https://user-images.githubusercontent.com/65057795/234497921-26faa02d-8f83-4ed2-b865-9744769ea8e4.png)



![Image](https://user-images.githubusercontent.com/65057795/234497955-f4a7dae5-e082-4654-bf8d-3694759595bf.png)
