### ISSUE TITLE
Incorrect responses to queries 

### ISSUE THREAD

**Issue by vijeeth-impactatscale** [AmakrushAI/app#77]
![WhatsApp Image 2023-04-15 at 1 03 19 PM (1)](https://user-images.githubusercontent.com/107395795/233038089-c5359ace-06d2-41fb-842e-619985328319.jpeg)
![WhatsApp Image 2023-04-15 at 1 03 19 PM (2)](https://user-images.githubusercontent.com/107395795/233038095-aed6b588-4451-47e0-8e31-f29a349b36ca.jpeg)
![WhatsApp Image 2023-04-15 at 1 03 19 PM](https://user-images.githubusercontent.com/107395795/233038103-7991784b-fc0b-4def-bf0d-5c10b78d4c0b.jpeg)

**Comment by GautamR-Samagra** [comment]
@ChakshuGautam These issues are being created due to the incorrect conversation flow prompt that makes GPT answer the question instead of going through the similarity search. We need to update the code to either include ai-tools SPacy search or my changes on the search
