### ISSUE TITLE
Caching Strategies

### ISSUE THREAD

**Issue by aashutosh-samagra** [AmakrushAI/app#8]
- [ ] Reduce the prompt size - BERT to summarize the context if it is too big. Define too big
- [ ] How to get `concept` that the user is talking about without OpenAI. (Box 13)
- [x] Use similarity search (say threshold - 99.9) for searching all of the previous prompts to see if we have an OpenAI response ready from them. Currently, it takes ~10 seconds for OpenAI to respond.

**Comment by ChakshuGautam** [comment]
@GautamR-Samagra to schedule a call for Prompt Management.

**Comment by ChakshuGautam** [comment]
Qualitative Feedback on Response Time - OK
