### ISSUE TITLE
Error message coming even before it is required

### ISSUE THREAD

**Issue by aashutosh-samagra** [AmakrushAI/app#81]
Error message surrounding delay in response are coming too soon , long before they are required. 
Summarizing the issues below - 

1. Error message is coming before it needs to 

2. Response is coming after error message hence making it redundant/ confusing

@ChakshuGautam can we assign this to someone

![Image](https://user-images.githubusercontent.com/122012226/233579469-7c18cfc0-17c2-45f0-b9e7-6a7f1e0acf53.png)

![Image](https://user-images.githubusercontent.com/122012226/233579513-5c53d2a2-780d-442b-abf2-254ad57d59a9.png)

**Comment by ChakshuGautam** [comment]
@prtkjakhar can you share with the team the account for Flagsmith and how to update this parameter?
