### ISSUE TITLE
Prompt fixes - coreference

### ISSUE THREAD

**Issue by GautamR-Samagra** [AmakrushAI/app#86]
A few issues with prompt : 
- [ ] Repeating the same question: Makes GPT answer the questions instead of providing coreference. Also same with similar questions 
- [ ] Remove Output / expert content from the response provided 
- [ ] Prompt is slow (too many tokens)

**Comment by ChakshuGautam** [comment]
GPT 4 for coref when I know GPT3 is wrong?
