### ISSUE TITLE
Data Mapping: Finalization of Model

### ISSUE THREAD

**Issue by aashutosh-samagra** [AmakrushAI/app#9]
@GautamR-Samagra  
[Colab](https://colab.research.google.com/drive/1dkVcPEr70Gr8y1L1b2ELqoU4YJ7dNt40#scrollTo=PRt4AzAWjeSI)

**Comment by ChakshuGautam** [comment]
Priority

1. [x] Make it work
2. [ ] Accuracy - Framework
3. [ ] Optimization - Plan

**Comment by GautamR-Samagra** [comment]
Adding the link to the collab [here](https://colab.research.google.com/drive/1dkVcPEr70Gr8y1L1b2ELqoU4YJ7dNt40#scrollTo=PRt4AzAWjeSI)

One just needs to run all the cells to see an example of the conversational flow enabled. 

For running custom prompts, one can use the function 'add_to_chat'

chat_hist, final_prompt, summarise_convo_result_dic  = add_to_chat( prompt,chat_hist, refresh = False ,chat_cutoff = 3  )

chat_hist is the history of the chat so far. You can use the argument refresh = True for a new chat. 
prompt : This is where the question one needs to ask GPT can be passed.  
chat_cutoff:  These are the window for the number of last n chats that are included for chat.  
refresh:  This should be set to True for new conversations. One can create chat_hist as an empty list (chat_hist=[]) 

An example of chat_hist that comes as output is shown below: 

[{'id': 1,
  'User': 'What scheme can i use to set up a broiler farm',
  'AI': 'The user can use the "Support to Farmers for Broiler Farming (500 Bird Capacity) under Deep Litter System" scheme to set up a broiler farm. The scheme has an outlay of Rs. 2968.00 lakhs, out of which the State Plan funding is Rs. 2966.40 lakh (40% of the total project cost). Additionally, there is an "Establishment of Small Scale Poultry Hatchery" scheme that the user may find useful for setting up a poultry hatchery. The scheme provides eligible individuals with subsidies for constructing and purchasing equipment for a new hatchery unit. However, there is no information available on any specific scheme or loan that can be used for broiler poultry farming from the Bank of India in Odisha.'},
 {'id': 2,
  'User': 'What is the elgibilty criteria for this scheme? ',
  'AI': 'The eligibility criteria for the "Support to Farmers for Broiler Farming (500 Bird Capacity) under Deep Litter System" scheme in Odisha, India is that willing farmers/entrepreneurs/ST, SC beneficiaries can apply online or in the prescribed format to the respective Block Veterinary Officer through local Livestock Inspector/ Veterinary Technician/Sub Assistant Veterinary Surgeon. All beneficiaries covered under the Scheme should mandatorily be Aadhaar linked to avoid duplication. After the joint verification of the proposed poultry unit, the District Level Committee chaired by the District Collector shall approve the final list of beneficiaries of the District. Each beneficiary will be provided a maximum of 40% subsidy of Rs 72,000 per broiler unit. The selection of beneficiaries must be made with Aadhar linking at the time of submission of application, and priority should be given to Women SHGs, ST, SC farmers.'}]
