### ISSUE TITLE
Avoid mentioning that the provided context is not relevant

### ISSUE THREAD

**Issue by GautamR-Samagra** [AmakrushAI/app#92]
Some responses face the issue that it mentions the phrase "The provided context is not about 'X'." We need to avoid showing the message

![provided context issue](https://user-images.githubusercontent.com/102940730/235884728-4ce31d05-72ea-4e7b-9ae2-d93120daa952.jpeg)

**Comment by ChakshuGautam** [comment]
@GautamR-Samagra figure out a way that removes this from the response.
